// Aggregated tests generated by LLM (demo input)
#include <gtest/gtest.h>
extern "C" {
#include "../src/hash_table.h"
}


TEST(GeneratedSuite, InsertAndGetWorks) {
    HashTable* t = hash_table_create(8);
    ASSERT_TRUE(hash_table_insert(t, "a", 1));
    int v = -1;
    ASSERT_TRUE(hash_table_get(t, "a", &v));
    EXPECT_EQ(v, 1);
    hash_table_destroy(t);
}

// 黑名单案例：包含 MOCKER(，应整段删除


// 编译错误案例：缺少符号，需根据编译错误删除该用例


// 运行失败案例：逻辑断言错误，运行后应删除
TEST(GeneratedSuite, RuntimeFailure) {
    HashTable* t = hash_table_create(5);
    EXPECT_EQ(hash_table_size(t), 999);
    hash_table_destroy(t);
}
